### ISSUE TITLE
Page feedback: support Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [google/docsy#1302]
Universal Analytics (UA) is deprecated. For details, see #1096. Here's some of the code associated with the page feedback feature: https://github.com/google/docsy/blob/d9bf98b876d74772b850ef910c6f59b898f61ccf/layouts/partials/feedback.html#L37-L53

This still uses the `analytics.js` library's `ga()` function. Note that this code is **incompatible with GA4** because of the library that is used and the event name, as is explained below.

### Tasks

- [x] [Migrate from analytics.js to gtag.js](https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs) - #1177
- [x] #1727
- [x] Fix event emitting code that calls `gtag` - #1726
  - [x] Confirm that `page_helpful` events are being emitted, with a default value of 100 for "yes" and 0 for "no" responses:
    - [x] For docsy.dev
    - [x] For example.docsy.dev
- [x] Add entry to the CHANGELOG
- [x] Update the docs, [Access the feedback data](https://www.docsy.dev/docs/adding-content/feedback/#access-the-feedback-data) in particular - #1726
- [x] Add a comment to #1426

---

Notes:

- Interestingly, Kubernetes docs had switched to using `gtag.js` in their override of [layouts/partials/feedback.html](https://github.com/kubernetes/website/blob/main/layouts/partials/feedback.html) already 4 years ago
- Indirectly related:
  - #175

/cc @caniszczyk @nate-double-u

**Comment by chalin** [comment]
Note: the use of `click` as a custom event name _might not prevent_ projects from accessing page-feedback event data (I'm still exploring how to do this in GA4), but it does seem to make it unnecessarily harder when the same event name is also used by GA4 for another purpose.

**Comment by chalin** [comment]
In the interim, it seems that projects can define an event-modification rule through the analytics console interface, to change the event name of page-feedback events to `page_helpful` from `click`. For extra details, see https://github.com/kubernetes/website/issues/37657#issuecomment-1301548361.

Thanks for the pointer to the relevant GA4 doc pages @emckean! 🧡

**Comment by jmichelgarcia** [comment]
_Thank you for the pointers here, I just spent one hour trying to figure out this_

**Comment by chalin** [comment]
All done!
