### ISSUE TITLE
Reintroduce RTL support using BSv5 RTLCSS

### ISSUE THREAD

**Issue by chalin** [google/docsy#1442]
In our move to Bootstrap v5 (BSv5), we are adopting the Bootstrap approach to RTL, as described in https://getbootstrap.com/docs/5.3/getting-started/rtl/. The good news is that we don't have to rename all properties that have [logical][] counterparts (at least for now), since [RTLCSS] handles their [translation appropriately].

### 24H2 work

- [x] Starting over with the strategy of using a single "main" CSS file per page, using an adapted RTL CSS for RTL pages:
    #2093
- [x] Review of 24H1 PRs that might need to be totally or partially reverted:
  - [x] #1443 - nothing to revert
  - [x] #2002 - ok except for `layouts/partials/head-css.html`, which is being reworked.
    Reverted via #2093
  - [x] #2020 & #2021 - nothing to revert
  - [x] #2018 - reverted via #2093
  - [x] #2025 - reverted via #2096
- [x] Create an `rtl` branch to be used during development
    **Branch preview**: https://rtl--docsydocs.netlify.app/
- [x] On `rtl` branch, set the `en` language as `rtl` for testing purposes - #2095
- [x] Old 24H1 issues that go away with #2093:
  - [x] #2003
  - [x] #2005
- [x] Test it out on the Docsy example
- [x] Cleanup - #2097
- [x] Update the UG - #2098

### 24H1 work - some of it reverted in H2

Entries processed (either ok as is, or reverted in whole or part), are marked with ⤴.

- [x] ⤴ Drop import of custom Docsy RTL styling, which was designed for Bootstrap v4 - #1443 
- [x] ⤴ #2002, fixing
    #2004
- [x] ⤴ #2020
    #2021
- [x] ⤴ #2018
  - [x] #829
  - [x] #2011
- [x] ⤴ #2025

---

Related:

- https://github.com/kubernetes/website/issues/45077
- https://github.com/kubernetes/website/issues/22730

Notes:

- Context: #470
- Would a switch to Bootstrap's RTL solution help address the following as well:
  https://github.com/matrix-org/docsy/issues/1? 
  Related(?): #605

Other:

- https://github.com/twbs/bootstrap/blob/cf9454caa00872899215603e5e036d9a824b1b11/package.json#L46

[logical]: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties
[RTLCSS]: https://rtlcss.com
[translation appropriately]: https://rtlcss.com/learn/getting-started/why-rtlcss/

**Comment by nate-double-u** [comment]
I think we may need some upstream help to support an Arabic localization for the kubernetes.io website (using Docsy as a theme).
* https://github.com/kubernetes/website/pull/44902

And to link this issue to the Kubernetes site more generally, I think solving this issue will also go toward solving https://github.com/kubernetes/website/issues/22730

/cc @mboukhalfa, @a-mccarthy, @sftim

**Comment by chalin** [comment]
All: as I mentioned in Slack, BS's [RTL support is experimental](https://getbootstrap.com/docs/5.3/getting-started/rtl/#get-familiar):

> **Bootstrap's RTL feature is still experimental** and will evolve based on user feedback. Spotted something or have an improvement to suggest? [Open an issue](#), we'd love to get your insights.

**Comment by a-mccarthy** [comment]
+1 @nate-double-u, this would help enable new languages that have started or expressed interest in localizating Kubernetes documentation.

cc: @seokho-son

**Comment by chalin** [comment]
@a-mccarthy @seokho-son : if you (and members of your community) could upvote this issue, it would help me assess the relative importance of the feature. Thanks.

**Comment by mboukhalfa** [comment]
+1 this important since Arabic localization is in progress and expected to be alive on k8s website but the RTL issues are blocking even the preview of the progress ! this issue will greatly help

**Comment by Metal-Bat** [comment]
loved the result
gona test it more surly

it had grate positioning and no weird display of persian characters
thanks for the effort
(translation was kinda clean just fixed a verb in pull request)

one more request kinda not sure is this the place for it or not
we lost the creator of 'vazir font' to cancer and we kinda like at least try to move a lot of translation project use this font (and it is a great honestly and it was defualt for alot of devices from the beginning)
is it posable to set  in this font?
https://github.com/Rava-milad/vazir-font

**Comment by chalin** [comment]
Thanks for taking a first look, and your willingness to try it out more thoroughly @Metal-Bat.

I'm going to move ahead and prepare the next official release of Docsy (https://github.com/google/docsy/issues/1944).

As for changing the font, see https://www.docsy.dev/docs/adding-content/lookandfeel/#fonts. I'll let others comment on how they adjust and/or include fonts, be it for multilingual projects or otherwise. 

Closing this as it seems complete. I'll reopen or comment if there is more work to be done.
