### ISSUE TITLE
Improve support for display of mathematical formulae

### ISSUE THREAD

**Issue by deining** [google/docsy#1837]
As of hugo v.0.122.0, you can do [LaTeX or TeX typsetting](https://gohugo.io/content-management/mathematics) directly from Markdown using standard syntax.

**Tasks**:
- [x] user guide: adapt and update section on math typesetting
- [x] retrieve scripts for display of mathematical formulae at build time (not at run time any more)
- [x] always retrieve latest version of scripts by default while allowing to stipulate a custom version in config file 
- [x] user guide + scripts:  drop support for hugo versions below 0.93
