### ISSUE TITLE
Hugo 0.125.x issues tracker: GA4, opengraph

### ISSUE THREAD

**Issue by chalin** [google/docsy#1907]
### Opengraph issues

- [x] https://github.com/gohugoio/hugo/issues/12418

### Hugo GA templates have changed or been dropped

For context, see:

- https://github.com/gohugoio/hugo/pull/12299

~(This hasn't landed yet in Hugo.)~ This landed in 0.125.x.

---

### Tasks

- [x] #1930
  - [x] #1931
- [x] #1939
- [x] Upgrade to Hugo 0.125.4+
  - [x] #1950
  - [ ] Use `hugo-extended` from NPM

**Comment by chalin** [comment]
Repurposing this issue from "Hugo GA templates have changed or been dropped" to more generally be a "Hugo 0.125.x issues tracker".
