### ISSUE TITLE
Release 0.11.0 preparation

### ISSUE THREAD

**Issue by chalin** [google/docsy#1944]
### Issues/PRs in scope

- [x] #1435
- [x] #2030
- [x] #1442
- [x] #2019
- [x] #2100

### _Candidate_ issues/PRs in scope (moved to #2108)

- [ ] #2001
- [ ] #2035
  - [ ] Can the following be reworked? #2057
- [ ] #1537
- [ ] #1841
- [ ] #1904
- [ ] #1987
- [ ] #1995
- [ ] #1996
- [ ] Top rated issues: https://github.com/google/docsy/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
- [ ] https://github.com/google/docsy/labels/i18n
- [ ] #2026

Time permitting:

- [ ] #1510
- [ ] #1852
- [ ] #2090

Also see:

- [milestone 24Q2](https://github.com/google/docsy/milestone/11)
- [milestone 24Q3](https://github.com/google/docsy/milestone/12)
- [milestone 24Q4](https://github.com/google/docsy/milestone/13)

### Release-prep checklist

For the complete instruction set, see [Publishing a release](https://github.com/google/docsy/blob/main/CONTRIBUTING.md#publishing-a-release):

- [x] Update Changelog: for inspiration, go over changes since last release https://github.com/google/docsy/compare/v0.10.0...main - #2101
- [x] Update the Docsy version in `package.json` and [userguide/hugo.yaml](https://github.com/google/docsy/blob/main/userguide/hugo.yaml)
- [x] Test pre-release from branch: 👍🏻 
- ~Pre-release patches?~
- [x] Create and push new version tag
- [x] Create and publish the new release 🎉

Docsy example followup (tracked separately):

- https://github.com/google/docsy-example/pull/329

### Related

- #1812
- https://github.com/google/docsy/compare/v0.10.0...main
