### ISSUE TITLE
Languages menu in side nav design issues: mispositioned and more

### ISSUE THREAD

**Issue by chalin** [google/docsy#2001]
Consider the image below. Here are the issues:

- [x] The menu appears far to the right, rather than below the menu title. **Fixed** a while a go this seems.
- [x] The language dropdown needs left margin or padding
  - [x] Fix for regular sidebar - #2183
  - [ ] Fix for foldable sidebar - ...
- [x] Text color:
  - [x] Menu title text color seems off - #2183
  - [x] Menu entry text doesn't appear to be of the right color - #2183
- [x] #2035

---

> <img width="444" alt="Screen Shot 2024-05-16 at 03 59 53" src="https://github.com/user-attachments/assets/b04ee91c-410d-4528-bc79-ec4715cb3b8d">

---

Related:

- #2131

**Comment by chalin** [comment]
Repurposed this to focus on design issues only. All done now. (Will track other issues separately.)

**Comment by chalin** [comment]
With `sidebar_menu_foldable: true`, the language menu in the sidebar has too much left padding still:

> <img width="266" height="322" alt="Image" src="https://github.com/user-attachments/assets/ff5f4fb8-cb84-4a17-a05e-4d6573380ed2" />
