### ISSUE TITLE
[CI] htmltest install is failing under Windows

### ISSUE THREAD

**Issue by chalin** [google/docsy#2062]
For details, see:

- https://github.com/wjdp/htmltest/issues/236

### Tasks

- [x] Implement a fix or workaround or disable part of the workflow:
  - [x] ~Disable the workflow for now, or~
  - [x] Disable link checking under Windows, but keep the build - #2064
- [ ] Re-enable link checking under Windows once the upstream issue is resolved.

**Comment by chalin** [comment]
- Pre-0.17.0 triage campaign: #2717
- Link checking now runs on Lychee; the htmltest install is gone from CI.
