### ISSUE TITLE
Release 0.12.0 preparation

### ISSUE THREAD

**Issue by chalin** [google/docsy#2108]
### Issues/PRs in scope

- [x] #2120 
  - [x] Also see followup items in #2120
- [x] #944
- [x] #2243

Also see:

- [milestone 24Q4](https://github.com/google/docsy/milestone/13)
- [milestone 25Q1](https://github.com/google/docsy/milestone/14)
- [milestone 25Q2](https://github.com/google/docsy/milestone/15)

### Release-prep checklist

For the complete instruction set, see [Publishing a release](https://github.com/google/docsy/blob/main/CONTRIBUTING.md#publishing-a-release):

- [x] Update Changelog: for inspiration, go over changes since last release https://github.com/google/docsy/compare/v0.11.0...main - #2101
- [x] Update the Docsy version in `package.json` and [userguide/hugo.yaml](https://github.com/google/docsy/blob/main/userguide/hugo.yaml)
- [x] Test pre-release from branch: 👍🏻 
- Pre-release patches?
- [x] Create and push new version tag
- [x] Create and publish the new release 🎉

Docsy example followup (tracked separately):

- https://github.com/google/docsy-example/pull/368

### Other / related

- #1944
- #2266
- https://github.com/google/docsy/compare/v0.11.0...main
