### ISSUE TITLE
Shortcodes: drop support for pre-Hugo-0.54.x behavior of `{{% %}}`

### ISSUE THREAD

**Issue by chalin** [google/docsy#939]
Here is some context:

- #87 

While the change introduced by that PR was relevant at the time (during a transition period from Hugo 0.54.x to 0.55+), we now only officially support the latest version of Hugo. So, all shortcodes making use of

```
{{ $_hugo_config := `{ "version": 1 }` }}
```

should have that line removed, and the shortcode adjusted, if necessary.

<details><summary>File list</summary>

```console
$ find . -type f -not -path "*/node_modules/*" -exec grep -le '_hugo_config' {} \;
./layouts/shortcodes/alert.html
./layouts/shortcodes/blocks/cover.html
./layouts/shortcodes/blocks/section.html
./layouts/shortcodes/blocks/lead.html
./layouts/shortcodes/pageinfo.html
```

</details> 

### Tasks

- [x] `layouts/shortcodes/alert.html` - #941
- [x] `layouts/shortcodes/blocks/cover.html` - #2480
- [x] `layouts/shortcodes/blocks/section.html` - #1472
- [x] `layouts/shortcodes/blocks/lead.html` - #1398
- [x] `layouts/shortcodes/pageinfo.html` - #2480
